### ISSUE TITLE
`--flake` fails if the `outputs` contain a `__functor`

### ISSUE THREAD

**Issue by nrdxp** [nix-community/nix-eval-jobs#134]
This command always fails on a flake whos `outputs` contains a `__functor` attribute. The error is a type where target is said to be a function and should be an attribute-set, even if the flake uri points to a valid attribute-set.

**Comment by Mic92** [comment]
Does `nix build` handle this properly?

**Comment by nrdxp** [comment]
yes, iirc there used to be a similar issue with Nix but it has since been fixed.

**Comment by Mic92** [comment]
Ok, if you can point to the fix, I can apply this here as well.

**Comment by blaggacao** [comment]
https://github.com/NixOS/nix/pull/6404 :smile:
