### ISSUE TITLE
Support `--expr` cli argument?

### ISSUE THREAD

**Issue by jsoo1** [nix-community/nix-eval-jobs#38]
In the [README](https://github.com/nix-community/nix-eval-jobs#further-options) the cli positional argument says `nix-eval-jobs` accepts an expression but the implementation requires it be a filepath https://github.com/nix-community/nix-eval-jobs/blob/e4b14ac863d47283ec4b8c924d88a6a10948197d/src/nix-eval-jobs.cc#L36

**Comment by jsoo1** [comment]
I guess the question is whether `nix-eval-jobs` wants to support `--expr`.

**Comment by Mic92** [comment]
I guess it wouldn't hurt. I just don't need it myself, so I will probably not implement it myself.
