### ISSUE TITLE
What is the file supposed to look like?

### ISSUE THREAD

**Issue by jsoo1** [nix-community/nix-eval-jobs#42]
I was confused first by the fact that the cli's positional parameter is documented as `expr` but in fact only accepts a file. Then I was confused by the expected format of the file. Is it supposed to be a hydra jobset? If so, the hydra jobset documentation is currently giving a 500 error: https://hydra.nixos.org/job/hydra/master/manual/latest/download-by-type/doc/manual#idm140737315920320

_Originally posted by @jsoo1 in https://github.com/nix-community/nix-eval-jobs/issues/41#issuecomment-1058835360_

**Comment by Mic92** [comment]
Here an example: https://github.com/nix-community/nix-eval-jobs/blob/main/tests/test_eval.py#L46
https://github.com/nix-community/nix-eval-jobs/blob/main/tests/assets/ci.nix

**Comment by jsoo1** [comment]
I see so that's actually pretty close to what I have but I do have some attrs with "illegal" characters in the names. As far as I could tell that was a limitation of `findAlongAttrPath`. Is the attr name restriction actually an upstream issue?

**Comment by jsoo1** [comment]
Well yeah you are probably right.  My issue is that attr names can be quoted:
test.nix:
```nix
{ "foo.bar" = baz; }
```
Right now, `nix-eval-jobs test.nix` will fail with:
```ShellSession
error: attribute 'foo' in selection path '"foo.bar"' not found
```
Which might
a) Be totally expected, but some documentation about the correct file format would help.
b) Be a bug
I am now actually leaning towards "bug" since `attrPaths` are those things you give to commands like `nix-eval`.  I.E.:
```ShellSession
nix-eval --attr foo.bar test.nix
```
would fail with the same error.

**Comment by jsoo1** [comment]
I guess my expectation was that `nix-eval-jobs` would lazily walk a nix ast until all the leaf derivations were instantiated.  I  think `findAlongAttrPath` is an easy approximation of that, but does fall down when trying to address the full variety of possible nix expressions.

**Comment by evanrelf** [comment]
@jsoo1 I don't think the attribute path part of what you said is totally correct.

> Right now, `nix-eval-jobs test.nix` will fail with:
> 
> ```
> error: attribute 'foo' in selection path '"foo.bar"' not found
> ```
> ...
> ```
> nix-env -i -f test.nix --attr foo.bar
> ```
> 
> would fail with the same error.

The error is saying the path is `[ "foo.bar" ]`, but the `nix-env` command uses an attribute path like `[ "foo" "bar" ]`. And they're different:

```
nix-repl> attrs = { "foo.bar" = 1; foo = { bar = 2; }; }

nix-repl> attrs."foo.bar"
1

nix-repl> attrs.foo.bar
2
```

**Comment by jsoo1** [comment]
> The error is saying the path is `[ "foo.bar" ]`, but the `nix-env` command uses an attribute path like `[ "foo" "bar" ]`. And they're different:
> 
> ```
> nix-repl> attrs = { "foo.bar" = 1; foo = { bar = 2; }; }
> 
> nix-repl> attrs."foo.bar"
> 1
> 
> nix-repl> attrs.foo.bar
> 2
> ```

Yep! That's my point. Attribute names and attr-paths are not the same thing, but nix-eval-jobs is using attr-paths to approximate attribute names, thus the confusion.

**Comment by evanrelf** [comment]
> Yep! That's my point. Attribute names and attr-paths are not the same thing, but nix-eval-jobs is using attr-paths to approximate attribute names, thus the confusion.

Ah I see!

**Comment by Mic92** [comment]
This is a limitation it inherited from hydra-eval-jobs. If you have a saner way of walking the tree that maybe also fixes https://github.com/nix-community/nix-eval-jobs/issues/9 or https://github.com/nix-community/nix-eval-jobs/issues/10
I am happy to review pull requests :)

**Comment by jsoo1** [comment]
I have a couple patches that fit our needs I could prepare. However I think it might be worth asking what the design and spec might be before I submit them.

I feel like some compatibility with the notion of an "installable" upstream would be helpful.  I.E. a single derivation, or a list of derivations, or an attribute set of derivations.  (I think that is an exhaustive list). That would simplify the solution space quite a bit.

**Comment by Mic92** [comment]
I thinking sticking with whatever nix-build and friends do would be the best as this is what users expects.

**Comment by tomberek** [comment]
For the moment I patched it like this:
```
diff --git a/src/nix-eval-jobs.cc b/src/nix-eval-jobs.cc
index e144ad0..c8da0f2 100644
--- a/src/nix-eval-jobs.cc
+++ b/src/nix-eval-jobs.cc
@@ -244,8 +244,9 @@ static void worker(
                 for (auto & i : v->attrs->lexicographicOrder()) {
                     std::string name(i->name);
                     if (name.find('.') != std::string::npos || name.find(' ') != std::string::npos) {
-                        printError("skipping job with illegal name '%s'", name);
-                        continue;
+                        name= "\"" + name + "\"";
+                        /* printError("skipping job with illegal name '%s'", name); */
+                        /* continue; */
                     }
                     attrs.push_back(name);
                 }
```
But that is not ideal, I'm considering either:
```
{
 "attr": ["defaultPackage" "x86_64-linux" "AusweisApp2" "foo.bar"],
...
```
which can be used with lib.attrsets.attrByPath

or
```
{
  "defaultPackage" = {
     "x86_64-linux" = {
        "AusweisApp2" = {
          "foo.bar" = {
             "drvPath": "/nix/store/mz12n7jh394cc3fglz1sa0a9m9a4dp0b-AusweisApp2-1.22.3.drv",
            "name": "AusweisApp2-1.22.3",
            "outputs": {
                "out": "/nix/store/0qb0nal6s8y8mp26waw1n1fbvsqi2hjk-AusweisApp2-1.22.3"
             },
           "system": "x86_64-linux"
         }
      }
   }
 }
}
```
which would JustWork with builtins.fromJSON

**Comment by tomberek** [comment]
Thoughts on re-purposing the new profile format when evaluating a flake?
```
{
  "elements": [
    {
      "active": true,
      "attrPath": "legacyPackages.x86_64-linux.up",
      "originalUri": "flake:nixpkgs",
      "storePaths": [
        "/nix/store/4fhrjp3imq4amzx2psdj390vxdndyjwp-up-0.4"
      ],
      "uri": "github:NixOS/nixpkgs/b66b39216b1fef2d8c33cc7a5c72d8da80b79970"
    }
],
"version":1
```
Differences include not having the output names ("out" "dev" "man") and no drvPath.

**Comment by jsoo1** [comment]
I agree with doing something like `nix-build` I am not sure `nix-env -i` is the right command to mimic here.  `nix-build` looks at the expressions it was given and does `getDerivations` on them: https://github.com/NixOS/nix/blob/0e58affd3967d113e43811311db9ee090778a756/src/nix-build/nix-build.cc#L315.

`getDerivations` currently supports 1) a single derivation, 2) an attrset of derivations or 3) a list of derivations. I think I can put in a patch for that, if desired. (see https://github.com/NixOS/nix/blob/0e58affd3967d113e43811311db9ee090778a756/src/libexpr/get-drvs.cc#L337)

**Comment by jsoo1** [comment]
Alright. I brought my PR out of draft. It is in a pretty nicely working state, aside from flake support (which I don't think ought to be too much trouble). Thank you for your patience on this!

**Comment by jsoo1** [comment]
@tomberek I believe there is room in #43 to support a variety of flake formats. I would like to do them in a separate PR, if possible, though.

**Comment by jsoo1** [comment]
@adisbladis You mentioned that nested attrsets (and trees in general) are a goal of the project in #59 . Would you mind chiming in on this?  As far as I can tell so far, it seems like you are saying `nix-eval-jobs` is aiming to simply replace `nix-instantiate` but with derivations as the only primitive leaves in the ast?  I'm happy to keep the traversal behavior as before in #43 but it is just a more frustrating user experience when the parameters of the cli are unclear/implicit.

**Comment by adisbladis** [comment]
@jsoo1 Regarding the evaluation of trees one of my unstated goals was always to be able to evaluate nixpkgs, just as with `nix-env`.
With the addition of support for `recurseForDerivations` that can now be done :tada: 

See https://github.com/nix-community/nix-eval-jobs/pull/62#issuecomment-1108609153.
