### ISSUE TITLE
Collecting from unknown thread

### ISSUE THREAD

**Issue by tomberek** [nix-community/nix-eval-jobs#47]
When running nix-eval-jobs inside a nix sandbox'd build (using `store = $PWD/temp` to avoid complications with the real store) I get an error of "Collecting from unknown thread" after a few moments that I do not get when running the same eval (also with the modified store) normally. This seems to come from the Boehm GC, but not sure why in this case it happens. Setting `GC_DONT_GC=1` env var seems to be a workaround, but not sure if there is another approach or underlying issue.

thoughts?
- eval-store
- daemon
- shared memory
- memory limitations in sandbox

**Comment by jsoo1** [comment]
I ran into `Collecting from unknown thread` without a sandboxed store.  Might need to just set it as part of `nix-eval-jobs` because of the forking model.
