### ISSUE TITLE
nix {stable,2.3} support?

### ISSUE THREAD

**Issue by jsoo1** [nix-community/nix-eval-jobs#50]
I have a branch on my fork that I would like to upstream that compiles with nix@2.3.X. It is not feature-complete with the unstable version yet. It might be handy for users like us who aren't able to update our nix package yet.

**Comment by jsoo1** [comment]
Come to think of it, a simple branch for `stable` releases would also be nice. Arguably `stable` should be `main`, and `unstable` should be a branch of its own.

**Comment by jsoo1** [comment]
Looks like there is already a TODO for this in #51

**Comment by jsoo1** [comment]
Argh. And even more complicated is the fact that really we are talking about nixpkgs pins, not nix pins.

**Comment by adisbladis** [comment]
Stable (2.8.0) support was fixed in #61.
2.3 is a bit of a tall order since so much in the Nix code base has differed.

**Comment by jsoo1** [comment]
True. I think I can work on 2.3 support if you want to make a branch.

Thank you so much!

**Comment by Mic92** [comment]
nix 2.3 is pretty much EOL at this point. The next release of nixos won't have it.

**Comment by Mic92** [comment]
Sorry, 2.3 support is out of scope of this project. We can if you want link to your project.

**Comment by jsoo1** [comment]
That's fair enough. I can keep my fork for a while longer. We would of course like to move off of nix 2.3 ourselves.
