### ISSUE TITLE
Respect `recurseForDerivations`

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nix-eval-jobs#9]
The evaluator is currently recursing into all attribute sets, even those that don't have `recurseForDerivations`.

`repro.nix`
```nix
{ system ? builtins.currentSystem }:
{
  # This should build
  drvA = derivation {
    inherit system;
    name = "drvA";
    builder = ":";
  };

  recurse = {
    # Should build if this attribute exists
    # recurseForDerivations = true;

    # This should not build
    drvB = derivation {
      inherit system;
      name = "drvA";
      builder = ":";
    };
  };
}
```

```console
$ nix-eval-jobs ./repro2.nix 
warning: `--gc-roots-dir' not specified
{"attr":"drvA","drvPath":"/nix/store/rq8kvmi17gzqpm1y7idyj493hzpk6p89-drvA.drv","name":"drvA","system":"x86_64-linux"}
{"attr":"recurse.drvB","drvPath":"/nix/store/rq8kvmi17gzqpm1y7idyj493hzpk6p89-drvA.drv","name":"drvA","system":"x86_64-linux"}
```

**Comment by adisbladis** [comment]
Which code is typically responsible for taking `recurseForDerivations` into account in Hydra?
`hydra-eval-jobs` behaves exactly the same so this is not a regression in `nix-eval-jobs`.

**Comment by grahamc** [comment]
I'm fairly sure recurseForDerivations filtering is implemented in Nixpkgs, and not a feature of the Hydra / nix-eval-jobs / Nix evaluator.

**Comment by grahamc** [comment]
Perhaps here: https://github.com/NixOS/nixpkgs/blob/354ede9a7812a570f39a826f2b9541ce4248080b/pkgs/top-level/release-lib.nix#L144-L154

**Comment by grahamc** [comment]
Maybe not: https://github.com/NixOS/nix/search?q=sRecurseForDerivations

I'm not sure.

**Comment by zimbatm** [comment]
I don't know for Hydra but it's implemented on the nix side when invoking nix-instantiate or nix-build. See for example https://github.com/nixos/nix/blob/d1aaa7ef71713b6693ad3ddf8704ce62bab82095/src/libexpr/get-drvs.cc#L353-L362

**Comment by danielfullmer** [comment]
This took me longer than I'd like to admit to figure out, so I'll document here in case anyone else runs into this:

For hydra on nixpkgs, I believe Graham was right that it's being filtered in Nix here: https://github.com/NixOS/nixpkgs/blob/354ede9a7812a570f39a826f2b9541ce4248080b/pkgs/top-level/release-lib.nix#L144-L154
Between `packagePlatforms` and `mapTestOn`, it turns all non-derivations in the attrset tree into just an empty attrset, recursing into attrsets if `recurseForDerivations` is true.  For instance:
```nix
{
  a = {
    b = <drv>;
    c = 1234;
    recurseForDerivations = true;
  };
  d = {
     e = <drv2>;
  };
}
```
turns into
```nix
{
  a = {
    b = { x86_64-linux = <drv>; };
    c = {};
    recurseForDerivations = {};
  };
  d = {};
}
```
which `hydra-eval-jobs` / `nix-eval-jobs` can handle.  Note that even `a.recurseForDerivations = true` turns into `a.recurseForDerivations = {}`.

It is a little unfortunate that it's implemented differently for `nix-build` vs `nix-eval-jobs`/`hydra-eval-jobs`.
